# This is a config for E2B sandbox template.
# You can use template ID (mn0azanlg5dz0jmbfwlm) or template name (getUITest) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("getUITest") # Sync sandbox
# sandbox = await AsyncSandbox.create("getUITest") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('getUITest')

team_id = "21a816c6-ab96-45ac-96b0-111aaf824996"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "getUITest"
template_id = "mn0azanlg5dz0jmbfwlm"
